### ISSUE TITLE
Add contributors to a repo

### ISSUE THREAD

**Issue by felexkemboi** [Marcos8060/Soko-App#1]
Add Felex as one of your contributors then we will start working together on this. Google on how to add a contributor to a project.My email is felokemboi10@gmail.com

**Comment by felexkemboi** [comment]
I am killing 2 birds with one stone here,I am showing you how to use Issues  and also challenging you learn how to add contributors

**Comment by felexkemboi** [comment]
In most projects,you will see it has alot of issues, Issues are complains or features which are not clear to the users or other developers in the team. So someone just creates an issue then the owner of the project can attend to.

**Comment by Marcos8060** [comment]
ok I am getting you now so what's next brother

**Comment by felexkemboi** [comment]
Ofcourse in serious projects we will not be using these funny funny terms..

**Comment by felexkemboi** [comment]
The thing is,I want you to add me as a contributor to this project.Do you know how to add contributors to a project?

**Comment by Marcos8060** [comment]
I don't think I know how to do it yet haven't tried it before

**Comment by Marcos8060** [comment]
I have successfully added you as one of the contributors.
